### ISSUE TITLE
Refactor makes some things very difficult

### ISSUE THREAD

**Issue by peterbourgon** [circonus-labs/circonus-gometrics#15]
Previously:

``` go
import "github.com/circonus-labs/circonus-gometrics"

m := circonusgometrics.NewCirconusMetrics()
m.SubmissionUrl = s.URL
```

Now:

``` go
import (
    "github.com/circonus-labs/circonus-gometrics"
    "github.com/circonus-labs/circonus-gometrics/checkmgr"
)

m, _ := circonusgometrics.NewCirconusMetrics(&circonusgometrics.Config{
    CheckManager: checkmgr.Config{
        Check: checkmgr.CheckConfig{
            SubmissionUrl: url,
        },
    },
})
```

Are you sure this is a good idea? :)

_edit: got the initialization wrong_

**Comment by maier** [comment]
i will be updating https://github.com/maier/cgm-gk after i get some other pull requests completed.

**Comment by peterbourgon** [comment]
No worries! I'm refactoring too: https://github.com/go-kit/kit/pull/313. Let me get that merged before you do too much work :)

**Comment by maier** [comment]
i'm merging in some more updates. i've also update the cgm-gk code. when you get done with your refactoring let me know and i'll fork and do a PR to update the circonus module if you'd prefer.
