### ISSUE TITLE
Retry connection to Circonus

### ISSUE THREAD

**Issue by dadgar** [circonus-labs/circonus-gometrics#39]
When starting the go-metrics sink, an error is returned if the address is not resolvable. The sink should handle retrying internally.

This manifests itself in several HashiCorp tools: https://github.com/hashicorp/consul/issues/2567 and https://github.com/hashicorp/nomad/issues/2055.

If you see statsd sink it handles it as such: https://github.com/armon/go-metrics/blob/master/statsd.go#L92-L101

**Comment by maier** [comment]
It is using github.com/hashicorp/go-retryablehttp to handle retrying five times. How would you like situation handled when it can't complete the request (after already retrying five times)? The integration is handling the error the same way the other syncs do (https://github.com/hashicorp/nomad/blob/master/command/agent/command.go#L682-L685). 

That could be changed to be:

```go
sink, err := circonus.NewCirconusSink(cfg)
if err != nil {
    // log it and continue without the sync
} else {
    sink.Start()
    fanout = append(fanout, sink)
}
```
